language: objective-c

branches:
 only:
 - master

xcode_project: AnimatingLabel.xcodeproj
xcode_scheme: AnimatingLabel
osx_image: xcode8.1
xcode_sdk: iphonesimulator9.0


install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail && xcodebuild -project AnimatingLabel.xcodeproj -scheme AnimatingLabel -sdk iphonesimulator test | xcpretty -c
